### PR TITLE
transform 'mlmm' into a proper R package

### PR DESCRIPTION
**Pull request by timflutre**
I made no change to the R functions themselves, but major changes to everything else so that `mlmm` now is a proper R package.
- The 2 examples were turned into vignettes. To save space in the git repo, I would recommend deleting the 2 original `.Rdata` file now into the `misc/` sub-directory, as their content used for the vignettes now is in the `data/` sub-directory.
- I kept Vincent and Bjarni as the main authors, but I added Uemit as maintainer and me as contributor.

Let me know if there is any problem, but everything worked for me with R 3.2.2 on Linux, and I followed the advice from Hadley Wickahm's [book](http://r-pkgs.had.co.nz/). So it should also work fine on Windows and Mac OS X.

### CODE REVIEW

**Comment by timeu** [comment]
Looks good and  thank you for the pull request.
I will tell Bjarni and Vincent to have a brief look but I guess there shouldn't be any issues.

**Comment by visegura** [comment]
I just had a quick look, it looks very good to me. Thanks a lot Tim!

**Comment by timflutre** [comment]
Great, let me know once it's merged. Of course, there is room for improvement (for instance concerning the documentation of the various functions), but this can be done later as the vignettes already are detailed enough.

**Comment by timeu** [comment]
@timflutre: Merged it

**Pull request merged**
